export const INCREMENT_DATE = 'INCREMENT_DATE';
export const DECREMENT_DATE = 'DECREMENT_DATE';
export const ADD_TRANSACTION_ITEM = 'ADD_TRANSACTION_ITEM';
export const UPDATE_TRANSACTION_ITEM = 'UPDATE_TRANSACTION_ITEM';
export const DELETE_TRANSACTION_ITEM = 'DELETE_TRANSACTION_ITEM';